Make ci pass
SamVerschueren/dev-time pull request #18
Opened 2018-09-06 09:19 UTC by sinchang

2018-09-06 10:24 UTC, SamVerschueren requested changes
Thanks for updating this. I believe Node.js 6 allows us to use spreading as well instead of `Object.assign` on line 48.

```js
opts = {
    exclude: [],
    ...opts,
    pages: 10,
    dir: tempfile()
};
```

2018-09-06 10:24 UTC, SamVerschueren commented on .travis.yml
>    - '6'
```
- 10
- 8
- 6
```

2018-09-06 10:24 UTC, SamVerschueren commented on .travis.yml
> +cache:
Remove

2018-09-06 10:31 UTC, sinchang commented
spreading disallow in v6.14.4

2018-09-07 14:30 UTC, sinchang commented
@SamVerschueren ready for merging. thx

2021-11-30 12:49 UTC, closed without merging